let overallData = [
    { 
        city: "Bengaluru",
        country: "India",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Perfect: 27°C (feels 31°C)",
        aqi: "🌱 Great: 35 US AQI",
        internet: "🏎 Fast: 19Mbps (avg)",
        safety: "Great",
        expenses: "Cheap: €596 / mo",
        emojiImg: "😝",
        overall: "3.85/5",
        img: "assets/media/places-img/bengaluru-india-600px.jpg",
    },
    { 
        city: "Goa",
        country: "India",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Perfect: 28°C (feels 34°C)",
        aqi: "🌱 Great: 45 US AQI",
        internet: "🙂 Good: 9Mbps (avg)",
        safety: "Good",
        expenses: "Affordable: €1,219 / mo",
        emojiImg: "🙂",
        overall: "3.43/5",
        img: "assets/media/places-img/goa.jpg",
    },
    { 
        city: "Mumbai",
        country: "India",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥵 Too hot: 32°C (feels 42°C)",
        aqi: "🌱 Good: 67 US AQI",
        internet: "🙂 Good: 9Mbps (avg)",
        safety: "Good",
        expenses: "Affordable: €966 / mo",
        emojiImg: "🙂",
        overall: "3.72/5",
        img: "assets/media/places-img/mumbai.jpg",
    },
    { 
        city: "McLeod Ganj",
        country: "India",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Perfect: 22°C (feels 22°C)",
        aqi: "😐 Moderate: 90 US AQI",
        internet: "🏎 Fast: 20Mbps (avg)",
        safety: "Good",
        expenses: "Cheap: €790 / mo",
        emojiImg: "😝",
        overall: "3.08/5",
        img: "assets/media/places-img/macleod.jpg",
    },
    { 
        city: "Pokhara",
        country: "Nepal",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Perfect: 28°C (feels 30°C)",
        aqi: "🌱 Good: 61 US AQI",
        internet: "🙂 Good: 7Mbps (avg)",
        safety: "Good",
        expenses: "Cheap: €585 / mo",
        emojiImg: "😝",
        overall: "3.42/5",
        img: "assets/media/places-img/pokhra.jpg",
    },
    { 
        city: "Berlin",
        country: "Germany",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Nice: 18°C (feels 18°C)",
        aqi: "🌱 Great: 25 US AQI",
        internet: "🏎 Fast: 32Mbps (avg)",
        safety: "Good",
        expenses: "Pricey: €2,518 / mo",
        emojiImg: "🧐",
        overall: "4.5/5",
        img: "assets/media/places-img/berlin-germany-600px.jpg",
    },
    { 
        city: "Singapore",
        country: "Singapore",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥵 Too hot: 31°C (feels 40°C)",
        aqi: "🌱 Good: 65 US AQI",
        internet: "🚀 Super fast: 87Mbps (avg)",
        safety: "Good",
        expenses: "Okay: €2,321 / mo",
        emojiImg: "🙂",
        overall: "3.98/5 ",
        img: "assets/media/places-img/singapore-singapore-600px.jpg",
    },
    { 
        city: "London",
        country: "United Kingdom",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥶 Too cold: 13°C (feels 11°C)",
        aqi: "🌱 Great: 27 US AQI",
        internet: "🏎 Fast: 23Mbps (avg)",
        safety: "Good",
        expenses: "Too expensive: €3,554 / mo",
        emojiImg: "🧐",
        overall: "4.07/5",
        img: "assets/media/places-img/london-united-kingdom-600px.jpg",
    },
    { 
        city: "Sydney",
        country: "Australia",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥶 A bit cold: 17°C (feels 17°C)",
        aqi: "🌱 Good: 54 US AQI",
        internet: "🏎 Fast: 19Mbps (avg)",
        safety: "Good",
        expenses: "Pricey: €3,234 / mo",
        emojiImg: "🧐",
        overall: "3.74/5",
        img: "assets/media/places-img/sydney-australia-600px.jpg",
    },
    { 
        city: "Paris",
        country: "France",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥶 A bit cold: 17°C (feels 17°C)",
        aqi: "🌱 Great: 25 US AQI",
        internet: "🏎 Fast: 32Mbps (avg)",
        safety: "Good",
        expenses: "Too expensive: €3,389 / mo",
        emojiImg: "🧐",
        overall: "3.64/5",
        img: "assets/media/places-img/paris-france-600px.jpg",
    },
    { 
        city: "Tokyo",
        country: "Japan",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Perfect: 24°C (feels 24°C)",
        aqi: "🌱 Great: 21 US AQI",
        internet: "🏎 Fast: 31Mbps (avg)",
        safety: "Great",
        expenses: "Pricey: €2,614 / mo",
        emojiImg: "🧐",
        overall: "3.51/5",
        img: "assets/media/places-img/tokyo.jpg",
    },
    { 
        city: "New York City,NY",
        country: "United States",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Nice: 21°C (feels 21°C)",
        aqi: "🌱 Great: 11 US AQI",
        internet: "🏎 Fast: 34Mbps (avg)",
        safety: "Good",
        expenses: "Too expensive: €3,889 / mo",
        emojiImg: "🧐",
        overall: "4.07/5",
        img: "assets/media/places-img/new-york-city-ny-united-states-600px.jpg",
    },
    { 
        city: "Hamburg",
        country: "Germany",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥶 Too cold: 14°C (feels 13°C)",
        aqi: "🌱 Great: 21 US AQI",
        internet: "🏎 Fast: 38Mbps (avg)",
        safety: "Good",
        expenses: "Pricey: €3,118 / mo",
        emojiImg: "🧐",
        overall: "3.53/5",
        img: "assets/media/places-img/humburg.jpg",
    },
    { 
        city: "Colombo",
        country: "Srilanka",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥵 Too hot: 30°C (feels 39°C)",
        aqi: "🌱 Great: 11 US AQI",
        internet: "🙂 Good: 8Mbps (avg)",
        safety: "Good",
        expenses: "Cheap: €732 / mo",
        emojiImg: "😝",
        overall: "3.47/5",
        img: "assets/media/places-img/colombo.jpg",
    },
    { 
        city: "Lisbon",
        country: "Portugal",
        popularity: "popular",
        climate: "⛅",
        temperature: "🌞 Nice: 21°C (feels 21°C)",
        aqi:"🌱 Great: 27 US AQI" ,
        internet: "🏎 Fast: 27Mbps (avg)",
        safety: "Great",
        expenses: "Affordable: €1,683 / mo",
        emojiImg : "🙂",
        overall: "4.79/5",
        img: "assets/media/places-img/lisbon.jpg",
    },
    { 
        city: "Kuching",
        country: "Malaysia",
        popularity: "popular",
        climate: "⛅",
        temperature: "🥵 Too hot: 31°C (feels 41°C)",
        aqi: "🌱 Great: 38 US AQI",
        internet: "🏎 Fast: 17Mbps (avg)",
        safety: "Good",
        expenses: "Cheap: €728 / mo",
        emojiImg: "😝",
        overall: "3.39/5",
        img: "assets/media/places-img/kuching.jpg",
    },
]